### PR TITLE
Fix launch for no variants

### PR DESCRIPTION
**Pull request by DonnieWest**
This should fix launch (again) for builds with no variants and when we have both release and debug apks present 

Note: My current computer doesn't have a multi-flavor Android project on it, so I'd appreciate someone testing this against builds with and without variants. If no one else can, I'll get to it Monday

### CODE REVIEW

**Comment by sultanahamer** [comment]
@DonnieWest there are two issues here, which I fixed as below to test


1. Extra dot after the path. Not sure if its syntax issue, but lsp was crying so I removed a dot
```
Hunk 1 of 2                                                                                                                     │
│-    let l:apk = system('find ' . l:path . . ' -name "' . l:metadata["elements"][0]["outputFile"] . '" | tr "\n" " " | tr "//" "│
│+    let l:apk = system('find ' . l:path . ' -name "' . l:metadata["elements"][0]["outputFile"] . '" | tr "\n" " " | tr "//" "/"│
```

2. I think you forgot to rename capitalize to lowercase there were two capitalize functions present
```
Hunk 2 of 2
-function! android#capitalize(str)
+function! android#lowercase(str)

```
after fixing them, I am still seeing the issue as shown below. Same ^@ character at the end.

image

to fix it, I have used `trim` as below

```
Hunk 1 of 3
-    let l:metadata = json_decode(readfile(system('find ' . l:path . ' -name "output-metadata.json" | tr "\n" " " | tr "//" "/" | sed "s/ //g"' )))
+    let l:metadata = json_decode(readfile(trim (system('find ' . l:path . ' -name "output-metadata.json" | tr "\n" " " | tr "//" "/" ' )) ))
```

One important thing that's bothering me is the replace with `sed "s/ //g"` If the project directory name has a space in it, would it be replaced as well?

**Comment by sultanahamer** [comment]
@DonnieWest added multiple flavors to OpenContacts on a branch. Below is the link for the same

**Branch**: flavorsTest

https://gitlab.com/sultanahamer/OpenContacts/-/tree/flavorsTest

**Comment by sultanahamer** [comment]
@DonnieWest I have tested this pr with above changes and it is working with multiple flavors as well on mac.

The command I used to launch is `:AndroidLaunch demoDebug`

**I think it would break on linux or a filesystem which is case sensitive in filenames.**

The command formed to install apk is like this

```
vim-android: Installing /Users/sultanm/Projects/OpenContacts/app/build/outputs/apk/Demo/debug/app-demo-debug.apk  
```
The character D in `Demo` word here is capital which is not on the filesystem.

**Comment by DonnieWest** [comment]
Ooh, all good catches. Thanks @sultanahamer 

Looks like I need to fix:

* BSD `sed` is displaying different behavior than GNU `sed`
* File paths could have spaces
* Flavors and/or variants could have varying casing (I worked with capital flavors almost exclusively. Looks like I might need to split them differently)
* lowercase function is missing

Also, good catch on that `trim` function, that seems like it's solving what I was erroneously doing with `sed`

**Comment by DonnieWest** [comment]
@sultanahamer also, thanks for adding dimensions to OpenContacts. Super useful for testing this :)

I added an additional dimension to test how this works:

```
diff --git a/app/build.gradle b/app/build.gradle
index c491214..2b144fb 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -32,7 +32,7 @@ android {
             signingConfig signingConfigs.debug
         }
     }
-    flavorDimensions "version"
+    flavorDimensions "version", "environment"
     productFlavors {
         demo {
             // Assigns this product flavor to the "version" flavor dimension.
@@ -43,6 +43,24 @@ android {
             applicationIdSuffix ".demo"
             versionNameSuffix "-demo"
         }
+        dev {
+            // Assigns this product flavor to the "version" flavor dimension.
+            // If you are using only one dimension, this property is optional,
+            // and the plugin automatically assigns all the module's flavors to
+            // that dimension.
+            dimension "environment"
+            applicationIdSuffix ".dev"
+            versionNameSuffix "-dev"
+        }
+        prod {
+            // Assigns this product flavor to the "version" flavor dimension.
+            // If you are using only one dimension, this property is optional,
+            // and the plugin automatically assigns all the module's flavors to
+            // that dimension.
+            dimension "environment"
+            applicationIdSuffix ".prod"
+            versionNameSuffix "-prod"
+        }
         full {
             dimension "version"
             applicationIdSuffix ".full"

```

Which gives us an `assemble` task like `assembleFullProd` and outputs an apk at `app/build/outputs/apk/fullProd/debug/app-full-prod-debug.apk`

Switching the flavor to mixed casing `PrOdUcTiOn` results in a task called `assembleDemoPrOdUcTiOn` and apk at `app/build/outputs/apk/demoPrOdUcTiOn/debug/app-demo-PrOdUcTiOn-debug.apk`

So, uh, it seems a new strategy is needed to split these. I'll fix up our other outstanding issues and work on this more

**Comment by DonnieWest** [comment]
@hsanson that's a brilliant solution :1st_place_medal: 

If you have the time, feel free to just make this change. I won't get back to this until tonight at the earliest

**Comment by DonnieWest** [comment]
@hsanson got a sec and pushed up your provided solution. Confirmed it worked for me too

**Pull request merged**
